#!/usr/bin/env python3
"""
Alert Model for VeriRisk Phase 3

Automatically generates alerts when:
- Risk score crosses high threshold (>= 65)
- Early warning score triggers (>= 40)
- Risk level escalates (LOW → MEDIUM or MEDIUM → HIGH)
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, JSON, Index, Enum
from datetime import datetime
import enum
import logging
import sys
import os
os.environ["PYTHONUTF8"] = "1"
sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import Base, engine

logger = logging.getLogger(__name__)


class AlertType(str, enum.Enum):
    """Types of alerts generated by the system"""
    HIGH_RISK_ALERT = "HIGH_RISK_ALERT"
    EARLY_WARNING_ALERT = "EARLY_WARNING_ALERT"
    RISK_ESCALATION_ALERT = "RISK_ESCALATION_ALERT"


class AlertStatus(str, enum.Enum):
    """Alert status"""
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"


class Alert(Base):
    """
    Alert records for risk threshold breaches.
    
    Alert Conditions:
    - HIGH_RISK_ALERT: risk_score >= 65
    - EARLY_WARNING_ALERT: early_warning_score >= 40
    - RISK_ESCALATION_ALERT: risk_level transitions LOW→MEDIUM or MEDIUM→HIGH
    """
    __tablename__ = "alerts"
    
    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Protocol identifier
    pool_id = Column(String(100), nullable=False, index=True)
    
    # Alert type
    alert_type = Column(String(50), nullable=False, index=True)
    
    # Risk metrics at time of alert
    risk_score = Column(Float, nullable=False)
    risk_level = Column(String(20), nullable=False)
    
    # Human-readable message
    message = Column(String(500), nullable=False)
    
    # SHAP-based explanations
    top_reasons = Column(JSON, nullable=True)
    
    # Status tracking
    status = Column(String(20), default='active', index=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    acknowledged_at = Column(DateTime, nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    
    # Previous state (for escalation alerts)
    previous_risk_level = Column(String(20), nullable=True)
    previous_risk_score = Column(Float, nullable=True)
    
    # Indexes
    __table_args__ = (
        Index('ix_alerts_pool_status', 'pool_id', 'status'),
        Index('ix_alerts_type_status', 'alert_type', 'status'),
    )
    
    def __repr__(self):
        return f"<Alert(pool_id='{self.pool_id}', type='{self.alert_type}', status='{self.status}')>"
    
    def to_dict(self):
        """Convert to dictionary for API response"""
        return {
            'id': self.id,
            'pool_id': self.pool_id,
            'alert_type': self.alert_type,
            'risk_score': self.risk_score,
            'risk_level': self.risk_level,
            'message': self.message,
            'top_reasons': self.top_reasons,
            'status': self.status,
            'previous_risk_level': self.previous_risk_level,
            'previous_risk_score': self.previous_risk_score,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'acknowledged_at': self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            'resolved_at': self.resolved_at.isoformat() if self.resolved_at else None
        }


# Alert threshold constants
ALERT_THRESHOLDS = {
    'high_risk_score': 65,
    'early_warning_score': 40,
    'escalation_transitions': [
        ('LOW', 'MEDIUM'),
        ('MEDIUM', 'HIGH'),
        ('LOW', 'HIGH')  # Skip escalation
    ]
}


def init_alerts_db():
    """
    Initialize the alerts table.
    
    Creates the table if it doesn't exist.
    """
    try:
        Alert.__table__.create(engine, checkfirst=True)
        logger.info("✓ alerts table initialized")
    except Exception as e:
        logger.error(f"Error initializing alerts table: {e}")
        raise


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    init_alerts_db()
    print("✓ Alert table created successfully")
